<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Взаимная оценка' => 'Барактар',
    'Учебно-методический центр ГСФР (УМЦ)' => 'ФЧМКнын окуу-усулдук борбору (ОУБ)',
    'Create Gallery'=>'Добавить галерею',
    'Title'=>'Заголовок',
    'Main Img'=>'Основоной рисунок',
    'Galleries'=>'Галереи',
    'News'=>'Новости',
    'Document'=>'В виде документа',
    'Download'=>'Скачать',
    'Are you sure you want to delete this item?'=>'Вы уверенны что хотите удалить?',
    'Прием граждан'=>'Коомдук кабылдама',
    'Общественная приёмная'=>'Коомдук кабылдама',
    'Регистрация'=>'Катталуу',
    'Объявления'=>'Жарыялар',
    'Личный кабинет'=>'Колдонуучунун профили',
    'Подробнее'=>'Дагы маалымат',
    'Главная'=>'Башкы бет',
    'Все объявления'=>'Баардык жарыялар',
    'О Финансовой Разведке'=>'Финансылык Чалгындоо',
    'Адрес: г. Бишкек, ул. Тоголок Молдо 21 «А» (пересекает ул. Фрунзе)'=>'Дарек: Бишкек ш, Тоголок Молдо көч. 21 «А» (Фрунзе кесилиши)',
    'Техническая поддержка ЕИС: тел. 32-55-34,адрес электронной почты: it@sfr.kg'=>'БМСти техникалык колдоо:32-55-34, электрондук почтанын дареги: it@sfr.kg',
    'Государственная Служба Финансовой Разведки при Правительстве Кыргызской Республики'=>'Кыргыз Республикасынын Өкмөтүнө Караштуу Финансылык Чалгындоо Мамлекеттик Кызматы',
    //'Update'=>'Редактировать'
];
